import type {SubjectBank} from './types.ts';

export const ciencias:SubjectBank={subject:'Ciências',items:[
 ['Fontes e transformação de energia',1,'Qual destas é uma fonte de energia renovável?',['energia eólica','petróleo','carvão mineral','gás natural'],0,'O vento se renova continuamente. Petróleo, carvão e gás natural são combustíveis fósseis, que levam milhões de anos para se formar.'],
 ['Fontes e transformação de energia',2,'Em uma usina hidrelétrica, qual é a principal transformação de energia?',['energia potencial da água em energia elétrica','energia química em energia luminosa','energia nuclear em energia térmica','energia elétrica em energia química'],0,'A água represada tem energia potencial. Ao cair, ganha energia cinética, gira as turbinas, e o gerador a converte em energia elétrica.'],
 ['Fontes e transformação de energia',2,'Um painel solar fotovoltaico transforma:',['energia luminosa em energia elétrica','energia elétrica em energia luminosa','energia térmica em energia nuclear','energia sonora em energia elétrica'],0,'As células fotovoltaicas convertem a luz do Sol diretamente em corrente elétrica.'],
 ['Fontes e transformação de energia',2,'Um liquidificador ligado transforma principalmente:',['energia elétrica em energia mecânica (movimento)','energia mecânica em energia elétrica','energia química em energia elétrica','energia luminosa em energia térmica'],0,'O motor elétrico faz as lâminas girarem. Parte da energia também vira calor e som.'],
 ['Fontes e transformação de energia',2,'Qual é uma desvantagem das usinas termelétricas a carvão?',['emitem gases de efeito estufa e poluentes','dependem da força dos ventos','não funcionam à noite','precisam de marés'],0,'A queima de carvão libera CO₂ e outros poluentes que afetam o clima e a saúde.'],
 ['Fontes e transformação de energia',3,'O princípio da conservação da energia afirma que:',['a energia não é criada nem destruída, apenas transformada','a energia se perde totalmente a cada uso','só existe energia elétrica','as usinas criam energia do nada'],0,'Nas transformações, parte da energia pode virar calor “não aproveitado”, mas a quantidade total se conserva.'],

 ['Circuitos elétricos e consumo responsável',1,'Para uma lâmpada acender, o circuito elétrico precisa de:',['uma fonte, fios condutores e a lâmpada em um caminho fechado','apenas uma lâmpada','apenas fios','um interruptor aberto'],0,'A corrente só circula em circuito fechado. Com o interruptor aberto, o caminho é interrompido.'],
 ['Circuitos elétricos e consumo responsável',2,'Um chuveiro de 5.000 W fica ligado 30 minutos por dia durante 30 dias. Quanto ele consome no mês?',['75 kWh','150 kWh','2.500 kWh','7,5 kWh'],0,'Energia = potência × tempo = 5 kW × 0,5 h × 30 dias = 75 kWh.'],
 ['Circuitos elétricos e consumo responsável',2,'Em um circuito em série com três lâmpadas, se uma delas queimar:',['todas apagam','só ela apaga','as outras brilham mais','nada muda'],0,'Em série há um único caminho para a corrente. Se ele é interrompido, todas apagam. Nas casas, os aparelhos são ligados em paralelo.'],
 ['Circuitos elétricos e consumo responsável',2,'Qual unidade de energia aparece na conta de luz?',['quilowatt-hora (kWh)','volt (V)','ampère (A)','watt (W)'],0,'O watt mede potência; o kWh mede energia (potência × tempo), que é o que se paga.'],
 ['Circuitos elétricos e consumo responsável',2,'Qual material é um bom condutor de eletricidade?',['cobre','borracha','plástico','madeira seca'],0,'Metais como o cobre conduzem bem a corrente. Borracha e plástico são isolantes e revestem os fios.'],
 ['Circuitos elétricos e consumo responsável',3,'Qual atitude reduz o consumo de energia elétrica em casa?',['trocar lâmpadas incandescentes por LED','deixar aparelhos em modo de espera (stand-by)','abrir a geladeira muitas vezes','tomar banhos longos no chuveiro elétrico'],0,'Lâmpadas LED gastam bem menos energia para a mesma iluminação. As outras atitudes aumentam o consumo.'],

 ['Reprodução e sexualidade com respeito e informação',1,'Qual é o principal hormônio masculino produzido nos testículos?',['testosterona','insulina','adrenalina','estrogênio'],0,'A testosterona provoca as mudanças da puberdade masculina, como a voz mais grave e o crescimento de pelos.'],
 ['Reprodução e sexualidade com respeito e informação',1,'Em geral, onde ocorre a fecundação no corpo humano?',['nas tubas uterinas','no útero','nos ovários','na vagina'],0,'O espermatozoide encontra o ovócito na tuba uterina. O embrião depois se implanta no útero.'],
 ['Reprodução e sexualidade com respeito e informação',2,'Qual método, além de evitar gravidez, também protege contra infecções sexualmente transmissíveis (ISTs)?',['preservativo (camisinha)','pílula anticoncepcional','DIU','tabelinha'],0,'Só os preservativos (masculino ou feminino) formam uma barreira que também reduz a transmissão de ISTs.'],
 ['Reprodução e sexualidade com respeito e informação',2,'A puberdade é:',['a fase de mudanças corporais e hormonais que torna o corpo capaz de se reproduzir','uma fase que só ocorre em meninos','uma doença passageira','o fim do crescimento, aos 10 anos'],0,'Ela começa em idades diferentes para cada pessoa e envolve mudanças físicas e emocionais.'],
 ['Reprodução e sexualidade com respeito e informação',2,'A menstruação acontece quando:',['não há fecundação e a camada interna do útero se descama','ocorre a fecundação','o ovócito é fecundado no ovário','o espermatozoide chega ao útero'],0,'Sem gravidez, os hormônios caem e o endométrio preparado para receber o embrião é eliminado.'],
 ['Reprodução e sexualidade com respeito e informação',3,'Sobre o respeito ao próprio corpo e ao dos outros, qual afirmação está correta?',['Ninguém deve tocar o corpo de outra pessoa sem consentimento, e situações de abuso devem ser contadas a um adulto de confiança.','Se for alguém conhecido, não há problema em tocar sem permissão.','Segredos sobre toques que causam desconforto devem ser guardados.','Só os adultos têm direito sobre o próprio corpo.'],0,'Consentimento é essencial em qualquer idade. Canais de ajuda: responsáveis, professores, Conselho Tutelar e o Disque 100.'],

 ['Sistema Sol, Terra e Lua',1,'O que causa a sucessão dos dias e das noites?',['a rotação da Terra','a translação da Terra','as fases da Lua','a distância entre a Terra e o Sol'],0,'Ao girar em torno do próprio eixo (cerca de 24 h), cada lado da Terra fica voltado ou não para o Sol.'],
 ['Sistema Sol, Terra e Lua',2,'Qual é a principal causa das estações do ano?',['a inclinação do eixo da Terra durante a translação','a Terra ficar muito mais perto do Sol no verão','a rotação da Lua','os eclipses'],0,'A inclinação faz os hemisférios receberem luz solar com ângulos e durações diferentes ao longo do ano. A variação da distância ao Sol é pequena.'],
 ['Sistema Sol, Terra e Lua',1,'Quanto tempo dura, aproximadamente, uma volta da Terra ao redor do Sol (translação)?',['365 dias','24 horas','29,5 dias','7 dias'],0,'São cerca de 365 dias e 6 horas. Por isso, a cada 4 anos há um ano bissexto.'],
 ['Sistema Sol, Terra e Lua',2,'Quando é verão no Hemisfério Sul, que estação é no Hemisfério Norte?',['inverno','verão','primavera','outono'],0,'Os hemisférios têm estações opostas, porque um está mais inclinado para o Sol enquanto o outro está menos.'],
 ['Sistema Sol, Terra e Lua',2,'Por que vemos a Lua brilhar no céu?',['porque ela reflete a luz do Sol','porque tem luz própria','porque reflete apenas a luz da Terra','porque é uma estrela'],0,'A Lua não produz luz: é iluminada pelo Sol, como a Terra.'],
 ['Sistema Sol, Terra e Lua',3,'O solstício de dezembro (por volta do dia 21) marca, no Hemisfério Sul:',['o dia mais longo do ano','a noite mais longa do ano','dia e noite com a mesma duração','um eclipse solar'],0,'Em dezembro, o Hemisfério Sul está mais inclinado para o Sol: começa o verão e ocorre o dia mais longo.'],

 ['Fases da Lua e eclipses',1,'Quanto tempo dura, aproximadamente, o ciclo completo das fases da Lua?',['29,5 dias','7 dias','365 dias','24 horas'],0,'De uma lua nova à seguinte passam cerca de 29,5 dias (mês sinódico). Cada fase principal dura cerca de uma semana.'],
 ['Fases da Lua e eclipses',2,'Um eclipse solar acontece quando:',['a Lua fica entre o Sol e a Terra','a Terra fica entre o Sol e a Lua','o Sol fica entre a Terra e a Lua','a Lua está na fase cheia'],0,'A sombra da Lua atinge uma região da Terra e encobre o Sol. Por isso ocorre na lua nova.'],
 ['Fases da Lua e eclipses',2,'Um eclipse lunar só pode acontecer em qual fase?',['cheia','nova','crescente','minguante'],0,'É preciso que a Terra esteja entre o Sol e a Lua, o que ocorre na lua cheia.'],
 ['Fases da Lua e eclipses',2,'O que acontece na lua nova?',['a face iluminada da Lua está voltada para o lado oposto ao da Terra','vemos a Lua toda iluminada','a Terra faz sombra sobre a Lua','a Lua sai de sua órbita'],0,'A Lua está entre a Terra e o Sol, então quase não vemos sua parte iluminada.'],
 ['Fases da Lua e eclipses',3,'Por que não há eclipses todos os meses?',['porque a órbita da Lua é inclinada em relação à órbita da Terra','porque a Lua para de girar','porque o Sol muda de tamanho','porque as nuvens escondem os eclipses'],0,'A inclinação da órbita (cerca de 5°) faz o alinhamento exato de Sol, Terra e Lua acontecer só em algumas épocas.'],
 ['Fases da Lua e eclipses',2,'Qual é a forma segura de observar um eclipse solar?',['usar filtros próprios e certificados, sem nunca olhar diretamente para o Sol','usar óculos escuros comuns','olhar rapidamente a olho nu','usar uma radiografia'],0,'Óculos escuros e radiografias não bloqueiam a radiação perigosa. Olhar para o Sol pode causar lesões permanentes nos olhos.'],

 ['Clima e mudanças climáticas',1,'Qual é a diferença entre tempo atmosférico e clima?',['tempo é a condição do momento; clima é o padrão observado ao longo de muitos anos','são a mesma coisa','o clima muda a cada hora','o tempo é medido em décadas'],0,'“Hoje está chovendo” descreve o tempo. “Os verões aqui são chuvosos” descreve o clima.'],
 ['Clima e mudanças climáticas',2,'O efeito estufa natural:',['retém parte do calor e mantém a Terra habitável','é sempre prejudicial à vida','é causado só pelas queimadas','resfria o planeta'],0,'Sem ele, a Terra seria gelada. O problema é a intensificação do efeito estufa pelas atividades humanas.'],
 ['Clima e mudanças climáticas',2,'Qual gás, liberado na queima de combustíveis fósseis, é o principal responsável pela intensificação do efeito estufa?',['dióxido de carbono (CO₂)','oxigênio (O₂)','nitrogênio (N₂)','hélio (He)'],0,'Carros, indústrias e usinas a combustíveis fósseis liberam grandes quantidades de CO₂.'],
 ['Clima e mudanças climáticas',2,'Qual instrumento mede a pressão atmosférica?',['barômetro','termômetro','pluviômetro','anemômetro'],0,'Termômetro mede temperatura, pluviômetro mede chuva e anemômetro mede a velocidade do vento.'],
 ['Clima e mudanças climáticas',2,'O pluviômetro mede:',['a quantidade de chuva','a velocidade do vento','a umidade do ar','a temperatura'],0,'A chuva é medida em milímetros: 1 mm equivale a 1 litro de água por metro quadrado.'],
 ['Clima e mudanças climáticas',3,'Qual ação ajuda a reduzir as emissões de gases de efeito estufa?',['usar transporte coletivo ou bicicleta','desmatar para abrir pastagens','queimar lixo','deixar luzes acesas sem necessidade'],0,'Menos carros individuais significa menos queima de combustível. Desmatar e queimar aumentam as emissões.'],
]};
