import type {SubjectBank} from './types.ts';

export const educacaoFisica:SubjectBank={subject:'Educação Física',items:[
 ['Esportes e estratégias',1,'Qual destes é um esporte de invasão?',['basquete','vôlei','tênis','atletismo'],0,'Nos esportes de invasão, as equipes tentam ocupar o campo adversário para marcar pontos (basquete, futebol, handebol).'],
 ['Esportes e estratégias',2,'Qual destes é um esporte de rede ou quadra dividida?',['vôlei','handebol','futsal','rúgbi'],0,'No vôlei, a rede separa as equipes, sem contato direto entre os adversários.'],
 ['Esportes e estratégias',2,'O que é marcação individual?',['cada defensor acompanha um adversário específico','todos os jogadores atacam ao mesmo tempo','o goleiro sempre sai do gol','o time não marca ninguém'],0,'Na marcação por zona, ao contrário, cada defensor cuida de uma área da quadra.'],
 ['Esportes e estratégias',2,'O que significa fair play (jogo limpo)?',['respeitar as regras, os adversários e a arbitragem','vencer a qualquer custo','provocar o adversário','ignorar as regras'],0,'O fair play valoriza a ética esportiva e a convivência, dentro e fora de quadra.'],

 ['Jogos e práticas corporais',1,'Qual é a diferença entre jogo e esporte?',['o jogo tem regras flexíveis combinadas pelo grupo; o esporte tem regras oficiais e institucionalizadas','não há diferença','o jogo não tem regras','o esporte não tem regras'],0,'Um jogo pode adaptar regras ao espaço e aos participantes. O esporte segue regras de federações.'],
 ['Jogos e práticas corporais',2,'Qual brinquedo tem origem indígena no Brasil?',['peteca','xadrez','beisebol','golfe'],0,'A palavra “peteca” vem do tupi e significa algo como “bater com a mão”.'],
 ['Jogos e práticas corporais',2,'Sobre jogos eletrônicos e saúde, qual atitude é recomendada?',['equilibrar o tempo de tela com atividades físicas e descanso','jogar sem pausas','trocar horas de sono por jogo','ficar sem se movimentar'],0,'Pausas, movimento e sono adequado previnem problemas posturais, visuais e de sono.'],
 ['Jogos e práticas corporais',2,'O que caracteriza um jogo cooperativo?',['todos trabalham juntos para alcançar um objetivo comum','um participante vence e os outros perdem','não há objetivo','só adultos podem participar'],0,'Os jogos cooperativos desenvolvem comunicação, empatia e resolução coletiva de problemas.'],

 ['Saúde e atividade física',1,'Quanto tempo de atividade física a Organização Mundial da Saúde recomenda para adolescentes?',['em média, pelo menos 60 minutos por dia, de intensidade moderada a vigorosa','10 minutos por semana','5 horas seguidas uma vez por mês','não há recomendação'],0,'A OMS (2020) recomenda uma média de 60 minutos diários para crianças e adolescentes de 5 a 17 anos.'],
 ['Saúde e atividade física',2,'Para que serve o aquecimento antes do exercício?',['preparar músculos e articulações, reduzindo o risco de lesões','cansar o corpo antes de começar','substituir a hidratação','nada, é desnecessário'],0,'O aquecimento eleva a temperatura corporal e a circulação de forma gradual.'],
 ['Saúde e atividade física',2,'A resistência aeróbia é a capacidade de:',['manter um esforço por muito tempo, como numa corrida longa','levantar um peso muito grande uma única vez','alongar os músculos','reagir rapidamente a um sinal'],0,'Ela depende do coração e dos pulmões e melhora com atividades contínuas, como caminhar, pedalar e nadar.'],
 ['Saúde e atividade física',2,'Como deve ser a hidratação durante a atividade física?',['beber água antes, durante e depois do exercício','beber água só duas horas depois','substituir a água por refrigerante','não beber água'],0,'O suor faz perder água e sais minerais, que precisam ser repostos.'],

 ['Práticas de aventura e segurança',1,'Quais são exemplos de práticas corporais de aventura urbanas?',['skate e parkour','rafting e rapel em cachoeira','surfe no mar','montanhismo'],0,'As práticas urbanas usam elementos da cidade, como rampas, escadas e muros.'],
 ['Práticas de aventura e segurança',2,'Quais equipamentos de proteção são indicados para andar de skate?',['capacete, joelheiras e cotoveleiras','apenas chinelos','apenas óculos escuros','nenhum equipamento'],0,'Os equipamentos reduzem a gravidade de quedas, que são comuns no aprendizado.'],
 ['Práticas de aventura e segurança',2,'Quais são exemplos de práticas corporais de aventura na natureza?',['trilha, escalada e rafting','skate de rua','parkour em praças','patinação em pista'],0,'Elas acontecem em ambientes naturais e exigem planejamento, orientação e respeito ao meio ambiente.'],
 ['Práticas de aventura e segurança',2,'Qual é uma atitude segura nas práticas de aventura?',['avaliar os riscos, respeitar os próprios limites e praticar em locais adequados','fazer manobras difíceis sem treino','praticar sozinho em lugares perigosos','ignorar as condições do tempo'],0,'Segurança envolve preparo, equipamento, supervisão quando necessário e atenção ao ambiente.'],
]};
