import type {SubjectBank} from './types.ts';

export const geografia:SubjectBank={subject:'Geografia',items:[
 ['Dinâmica populacional e migrações',1,'O crescimento vegetativo (ou natural) de uma população é a diferença entre:',['a taxa de natalidade e a taxa de mortalidade','a imigração e a emigração','a população urbana e a rural','homens e mulheres'],0,'O crescimento vegetativo não inclui migrações. Somando as migrações, obtém-se o crescimento total.'],
 ['Dinâmica populacional e migrações',2,'O êxodo rural é:',['a migração do campo para a cidade','a migração da cidade para o campo','a migração entre países','o deslocamento de turistas nas férias'],0,'No Brasil, ele foi intenso entre 1950 e 1980, com a industrialização e a mecanização do campo.'],
 ['Dinâmica populacional e migrações',2,'Quem é considerado refugiado?',['a pessoa forçada a deixar seu país por guerra, perseguição ou grave violação de direitos','um turista','um estudante de intercâmbio','quem muda de bairro na mesma cidade'],0,'Os refugiados têm proteção prevista no direito internacional e não podem ser devolvidos a situações de risco.'],
 ['Dinâmica populacional e migrações',2,'O envelhecimento da população ocorre quando:',['a natalidade cai e a expectativa de vida aumenta','a natalidade aumenta muito','a expectativa de vida diminui','há muitas guerras'],0,'Com menos nascimentos e vidas mais longas, cresce a proporção de idosos, como acontece hoje no Brasil.'],
 ['Dinâmica populacional e migrações',2,'Uma pirâmide etária com a base larga indica:',['alta natalidade e população jovem','população majoritariamente idosa','baixa natalidade','migração de idosos'],0,'A base representa as faixas de idade mais novas. Base larga significa muitas crianças e jovens.'],
 ['Dinâmica populacional e migrações',3,'Um país tem 20 milhões de habitantes e área de 400.000 km². Qual é a sua densidade demográfica?',['50 hab/km²','20 hab/km²','500 hab/km²','5 hab/km²'],0,'Densidade = população ÷ área = 20.000.000 ÷ 400.000 = 50 habitantes por km².'],

 ['América Latina e regionalizações',1,'Qual critério separa a América Latina da América Anglo-Saxônica?',['histórico-cultural: a colonização e os idiomas predominantes','apenas o relevo','apenas o clima','o fuso horário'],0,'A América Latina foi colonizada principalmente por espanhóis e portugueses, que trouxeram línguas de origem latina.'],
 ['América Latina e regionalizações',2,'Qual país da América do Norte faz parte da América Latina?',['México','Canadá','Estados Unidos','Groenlândia'],0,'Pelo critério físico, o México está na América do Norte. Pelo critério histórico-cultural, está na América Latina.'],
 ['América Latina e regionalizações',2,'Quais são as línguas predominantes na América Latina?',['espanhol e português','inglês e alemão','francês e russo','chinês e japonês'],0,'Também há muitas línguas indígenas, como o quéchua e o guarani, além do francês no Haiti.'],
 ['América Latina e regionalizações',2,'Qual canal liga o Oceano Atlântico ao Oceano Pacífico pela América Central?',['Canal do Panamá','Canal de Suez','Estreito de Gibraltar','Canal da Mancha'],0,'O Canal do Panamá encurta muito as rotas marítimas. O de Suez liga o Mediterrâneo ao Mar Vermelho.'],
 ['América Latina e regionalizações',2,'O Mercosul é:',['um bloco econômico sul-americano','uma organização militar','uma moeda única para toda a América','um acordo apenas entre Estados Unidos e Canadá'],0,'Foi criado em 1991 por Brasil, Argentina, Paraguai e Uruguai para facilitar o comércio entre eles.'],
 ['América Latina e regionalizações',3,'Onde fica a Cordilheira dos Andes?',['no oeste da América do Sul','no leste do Brasil','no Caribe','apenas na América Central'],0,'Ela acompanha a costa do Pacífico, da Venezuela ao sul do Chile e da Argentina.'],

 ['África e diversidade territorial',1,'Qual é o maior deserto quente do mundo, localizado no norte da África?',['Saara','Atacama','Gobi','Kalahari'],0,'O Saara ocupa boa parte do norte africano. O Kalahari fica no sul do continente.'],
 ['África e diversidade territorial',2,'Qual é o rio mais extenso da África?',['Nilo','Congo','Níger','Amazonas'],0,'O Nilo atravessa vários países até o Mediterrâneo e foi essencial para a civilização egípcia.'],
 ['África e diversidade territorial',2,'Em que encontro as potências europeias dividiram o território africano entre si?',['na Conferência de Berlim, em 1884–1885','no Tratado de Tordesilhas','no Congresso de Viena','na Conferência de Yalta'],0,'As fronteiras foram traçadas sem considerar os povos que viviam em cada região.'],
 ['África e diversidade territorial',2,'Uma regionalização comum do continente africano o divide em:',['África do Norte (Setentrional) e África Subsaariana','África Latina e África Anglo-Saxônica','Oriente e Ocidente apenas','África Tropical e África Polar'],0,'O Saara funciona como divisor entre o norte, de maioria árabe e islâmica, e a porção subsaariana, de grande diversidade étnica.'],
 ['África e diversidade territorial',2,'Qual foi uma consequência das fronteiras impostas pelos colonizadores europeus?',['conflitos entre povos separados ou reunidos à força','a ausência total de conflitos','o fim da diversidade étnica','a unificação de todas as línguas'],0,'Grupos rivais ficaram no mesmo país, e povos com laços históricos foram separados, o que gerou tensões duradouras.'],
 ['África e diversidade territorial',3,'Em que país vigorou o apartheid, regime de segregação racial que terminou nos anos 1990?',['África do Sul','Egito','Nigéria','Marrocos'],0,'Nelson Mandela, preso por 27 anos, tornou-se presidente em 1994, após o fim do apartheid.'],

 ['Urbanização e desigualdades',1,'O que é urbanização?',['o aumento da população urbana em relação à rural','o aumento da população rural','o crescimento das florestas','a diminuição das cidades'],0,'Hoje a maior parte da população brasileira vive em áreas urbanas.'],
 ['Urbanização e desigualdades',2,'O que é uma metrópole?',['uma cidade principal que concentra serviços e influencia uma grande região','qualquer vila pequena','uma zona rural','uma cidade abandonada'],0,'São Paulo, Rio de Janeiro e Buenos Aires são exemplos de metrópoles latino-americanas.'],
 ['Urbanização e desigualdades',2,'A conurbação é:',['a junção das áreas urbanas de cidades vizinhas','a separação de bairros','a saída de moradores das cidades','a criação de parques'],0,'Com o crescimento, os limites entre os municípios deixam de ser percebidos na paisagem.'],
 ['Urbanização e desigualdades',2,'Qual problema urbano está ligado à desigualdade social?',['moradias precárias em áreas de risco','excesso de áreas verdes','falta de carros','poucos moradores'],0,'Sem acesso à moradia digna, muitas famílias vivem em encostas ou margens de rios, sujeitas a desastres.'],
 ['Urbanização e desigualdades',2,'Como a ONU costuma chamar uma cidade com mais de 10 milhões de habitantes?',['megacidade','vila','povoado','cidade média'],0,'São Paulo, Cidade do México e Buenos Aires estão entre as megacidades da América Latina.'],
 ['Urbanização e desigualdades',3,'Qual medida favorece a mobilidade urbana sustentável?',['priorizar transporte coletivo, ciclovias e calçadas','ampliar só as vias para carros','proibir ônibus','eliminar calçadas'],0,'Transporte coletivo e ativo reduz congestionamentos, poluição e emissões.'],

 ['Globalização e fluxos',1,'A globalização pode ser entendida como:',['a integração econômica, cultural e de comunicação entre os países','o isolamento dos países','o fim do comércio','a volta ao feudalismo'],0,'Ela se intensificou a partir do fim do século XX, com novas tecnologias de transporte e comunicação.'],
 ['Globalização e fluxos',2,'Qual é um exemplo de fluxo imaterial?',['uma transferência de dinheiro pela internet','o transporte de soja em navio','uma viagem de ônibus','uma carga de minério de ferro'],0,'Fluxos imateriais envolvem informações, dados e capitais. Os materiais envolvem mercadorias e pessoas.'],
 ['Globalização e fluxos',2,'Uma empresa transnacional é aquela que:',['tem sede em um país e filiais em vários outros','atua em um só bairro','é um órgão público municipal','é uma cooperativa local sem filiais'],0,'Elas distribuem produção e vendas pelo mundo em busca de mercados e custos menores.'],
 ['Globalização e fluxos',2,'Quais tecnologias aceleraram a globalização atual?',['a internet e os satélites de comunicação','o arado de madeira','o moinho de vento','o pergaminho'],0,'A comunicação instantânea permite coordenar negócios e trocar informações em escala global.'],
 ['Globalização e fluxos',2,'Por que se diz que a globalização é desigual?',['porque seus benefícios se distribuem de forma desigual entre países e pessoas','porque todos os países ganham igualmente','porque acabou com a pobreza','porque eliminou as fronteiras'],0,'Países e grupos com mais tecnologia e capital tendem a aproveitar mais as vantagens.'],
 ['Globalização e fluxos',3,'Qual bloco econômico adota uma moeda comum, o euro, em parte de seus países-membros?',['União Europeia','Mercosul','USMCA (antigo Nafta)','BRICS'],0,'A União Europeia é o bloco de integração mais avançado, com livre circulação de pessoas e, em muitos países, moeda única.'],

 ['Recursos naturais e impactos ambientais',1,'Qual destes recursos é renovável, se bem manejado?',['a água dos rios','o petróleo','o carvão mineral','o minério de ferro'],0,'A água se renova pelo ciclo hidrológico, mas pode se esgotar localmente se for poluída ou usada em excesso.'],
 ['Recursos naturais e impactos ambientais',2,'Qual é uma consequência do desmatamento na Amazônia?',['perda de biodiversidade e mudanças no regime de chuvas','aumento das espécies nativas','fim do efeito estufa','resfriamento global'],0,'A floresta recicla umidade que forma chuvas em outras regiões, inclusive no Centro-Sul do Brasil.'],
 ['Recursos naturais e impactos ambientais',2,'O assoreamento de um rio é:',['o acúmulo de sedimentos no leito, geralmente após a retirada da mata ciliar','o aumento da profundidade do rio','uma limpeza natural','a construção de pontes'],0,'Sem vegetação nas margens, a terra é levada para o rio, que fica mais raso e sujeito a enchentes.'],
 ['Recursos naturais e impactos ambientais',2,'O desenvolvimento sustentável busca:',['atender às necessidades atuais sem comprometer as gerações futuras','explorar ao máximo os recursos agora','proibir qualquer uso de recursos','crescer sem planejamento'],0,'A ideia une crescimento econômico, justiça social e preservação ambiental.'],
 ['Recursos naturais e impactos ambientais',2,'Qual impacto a mineração pode causar?',['contaminação de rios e rompimento de barragens de rejeitos','aumento da vegetação nativa','purificação da água','aumento do número de peixes'],0,'Os rompimentos de barragens em Mariana (2015) e Brumadinho (2019), em Minas Gerais, mostraram a gravidade desses riscos.'],
 ['Recursos naturais e impactos ambientais',3,'O que a América Latina exporta principalmente?',['commodities, como minérios e produtos agrícolas','principalmente aviões de alta tecnologia','principalmente softwares','principalmente navios'],0,'A dependência de produtos primários deixa as economias sensíveis às variações de preço no mercado internacional.'],
]};
