import type {SubjectBank} from './types.ts';

export const historia:SubjectBank={subject:'História',items:[
 ['Iluminismo',1,'Em que século o Iluminismo (o “Século das Luzes”) teve seu auge na Europa?',['XVIII','XV','XX','XII'],0,'O movimento ganhou força nos anos 1700 e influenciou as revoluções do final daquele século.'],
 ['Iluminismo',2,'Qual pensador iluminista defendeu a separação dos poderes em Executivo, Legislativo e Judiciário?',['Montesquieu','Voltaire','Adam Smith','Luís XIV'],0,'Em “O espírito das leis” (1748), Montesquieu propôs dividir o poder para evitar abusos.'],
 ['Iluminismo',2,'Quem escreveu “O contrato social”, obra que defende a soberania do povo?',['Jean-Jacques Rousseau','Isaac Newton','Napoleão Bonaparte','Cristóvão Colombo'],0,'Para Rousseau, o poder legítimo nasce de um pacto entre os cidadãos.'],
 ['Iluminismo',2,'O que as ideias iluministas criticavam?',['o absolutismo e os privilégios do clero e da nobreza','a ciência e a razão','a liberdade de expressão','a igualdade perante a lei'],0,'Os iluministas valorizavam a razão, a liberdade e a igualdade jurídica, contra o poder absoluto dos reis.'],
 ['Iluminismo',2,'A Enciclopédia, que reuniu e divulgou os conhecimentos da época, foi organizada por:',['Diderot e d’Alembert','Locke e Hobbes','Marx e Engels','Galileu e Kepler'],0,'Publicada na França a partir de 1751, ela espalhou as ideias iluministas.'],
 ['Iluminismo',3,'O liberalismo econômico, associado a Adam Smith, defendia:',['pouca intervenção do Estado na economia','controle total do Estado sobre os preços','o fim do comércio','a volta do sistema feudal'],0,'Em “A riqueza das nações” (1776), Smith argumentou que o mercado livre favorece a prosperidade.'],

 ['Revolução Industrial',1,'Em que país começou a Revolução Industrial, no século XVIII?',['Inglaterra','Brasil','Japão','Portugal'],0,'A Inglaterra reunia capital, matérias-primas, mão de obra e mercados para as fábricas.'],
 ['Revolução Industrial',2,'Qual invenção é símbolo da Primeira Revolução Industrial?',['a máquina a vapor','o computador','o avião','o telefone celular'],0,'A máquina a vapor, aperfeiçoada por James Watt, movimentou fábricas, trens e navios.'],
 ['Revolução Industrial',2,'Qual setor foi o primeiro a se mecanizar na Revolução Industrial?',['têxtil','automobilístico','informática','aeronáutico'],0,'A produção de tecidos de algodão foi a primeira a usar teares e fiadeiras mecânicas.'],
 ['Revolução Industrial',2,'Qual foi uma consequência social da Revolução Industrial?',['jornadas longas, trabalho infantil e crescimento desordenado das cidades','o fim do trabalho assalariado','a diminuição da população urbana','o fechamento das fábricas'],0,'Os operários enfrentavam condições duras, o que levou à organização de sindicatos.'],
 ['Revolução Industrial',2,'O ludismo foi:',['um movimento de trabalhadores que quebravam máquinas em protesto','um movimento artístico','um partido político francês','uma religião inglesa'],0,'Os luditas culpavam as máquinas pelo desemprego e pelos baixos salários.'],
 ['Revolução Industrial',3,'Quais fatores explicam o pioneirismo inglês na industrialização?',['reservas de carvão e ferro, capital acumulado e mão de obra disponível','a ausência de comércio','um território sem recursos naturais','a proibição de fábricas'],0,'O carvão alimentava as máquinas, o comércio gerava capital, e os cercamentos expulsaram camponeses para as cidades.'],

 ['Independência dos Estados Unidos',1,'Qual era a metrópole das Treze Colônias da América do Norte?',['Inglaterra','Espanha','França','Portugal'],0,'As Treze Colônias foram fundadas por ingleses na costa leste da América do Norte.'],
 ['Independência dos Estados Unidos',1,'Em que ano foi assinada a Declaração de Independência dos Estados Unidos?',['1776','1789','1822','1492'],0,'Foi assinada em 4 de julho de 1776. A guerra contra a Inglaterra continuou até 1783.'],
 ['Independência dos Estados Unidos',2,'O que levou os colonos a se revoltar contra a Inglaterra?',['o aumento de impostos e leis criadas sem representação dos colonos','a descoberta de ouro','uma invasão espanhola','a abolição da escravidão'],0,'Leis como a do Selo (1765) e a do Chá (1773) geraram o lema “nenhuma taxação sem representação”.'],
 ['Independência dos Estados Unidos',2,'A Festa do Chá de Boston (1773) foi:',['um protesto em que colonos jogaram ao mar um carregamento de chá','uma festa oficial do rei inglês','um tratado de paz','uma celebração religiosa'],0,'Foi uma reação à Lei do Chá e aumentou a tensão com a metrópole.'],
 ['Independência dos Estados Unidos',2,'Quem foi o principal redator da Declaração de Independência dos Estados Unidos?',['Thomas Jefferson','Abraham Lincoln','Napoleão Bonaparte','Simón Bolívar'],0,'Jefferson incorporou ideias iluministas, como o direito à vida, à liberdade e à busca da felicidade.'],
 ['Independência dos Estados Unidos',3,'Qual foi uma contradição da independência dos Estados Unidos?',['a Declaração falava em liberdade, mas a escravidão foi mantida','não existia escravidão nas colônias','as mulheres conquistaram o voto imediatamente','os povos indígenas receberam todas as terras'],0,'A escravidão só foi abolida no país em 1865, depois da Guerra Civil.'],

 ['Revolução Francesa',1,'Qual acontecimento de 1789 é considerado o marco inicial da Revolução Francesa?',['a Tomada da Bastilha','a Proclamação da República no Brasil','a Independência dos Estados Unidos','o início da Revolução Industrial'],0,'Em 14 de julho de 1789, a população de Paris invadiu a Bastilha, prisão que simbolizava o absolutismo.'],
 ['Revolução Francesa',2,'Qual era o lema da Revolução Francesa?',['Liberdade, Igualdade, Fraternidade','Ordem e Progresso','Deus, Pátria e Rei','Paz, Pão e Terra'],0,'O lema resume ideais iluministas. “Ordem e Progresso” é o lema da bandeira brasileira.'],
 ['Revolução Francesa',2,'Na França antes da Revolução, quem formava o Terceiro Estado?',['a burguesia, os camponeses e os trabalhadores urbanos','o clero','a nobreza','a família real'],0,'O Terceiro Estado era a maioria da população e pagava impostos, enquanto clero e nobreza tinham privilégios.'],
 ['Revolução Francesa',2,'Qual documento de 1789 afirmou que “os homens nascem e permanecem livres e iguais em direitos”?',['Declaração dos Direitos do Homem e do Cidadão','Constituição brasileira de 1824','Magna Carta','Tratado de Tordesilhas'],0,'Ela inspirou constituições e declarações de direitos no mundo todo.'],
 ['Revolução Francesa',2,'Quem governou durante o período conhecido como Terror (1793–1794)?',['os jacobinos, liderados por Robespierre','a nobreza, liderada por Luís XVI','os ingleses','Napoleão, já como imperador'],0,'Os jacobinos perseguiram opositores e realizaram muitas execuções na guilhotina.'],
 ['Revolução Francesa',3,'Qual acontecimento encerrou o ciclo revolucionário e levou Napoleão ao poder em 1799?',['o Golpe do 18 Brumário','a Tomada da Bastilha','a Independência do Haiti','a Queda do Muro de Berlim'],0,'Com o golpe, Napoleão tornou-se primeiro-cônsul e, em 1804, imperador.'],

 ['Independências na América Latina',1,'Qual foi o primeiro país da América Latina a se tornar independente, em 1804?',['Haiti','Brasil','Argentina','México'],0,'A independência do Haiti resultou de uma revolução de pessoas escravizadas contra a França.'],
 ['Independências na América Latina',2,'Quem liderou lutas de independência na Venezuela, Colômbia, Equador, Peru e Bolívia e ficou conhecido como “Libertador”?',['Simón Bolívar','Dom Pedro I','George Washington','Tiradentes'],0,'Bolívar sonhava unir a América do Sul, mas as antigas colônias formaram vários países.'],
 ['Independências na América Latina',2,'Quem eram os criollos na América espanhola?',['descendentes de espanhóis nascidos na América','espanhóis nascidos na Espanha','indígenas','africanos escravizados'],0,'Os criollos eram ricos, mas excluídos dos altos cargos, reservados aos chapetones (nascidos na Espanha). Por isso lideraram as independências.'],
 ['Independências na América Latina',2,'Qual acontecimento europeu enfraqueceu a Espanha e favoreceu as independências de suas colônias?',['a invasão da Espanha por Napoleão, em 1808','a Revolução Russa','a Primeira Guerra Mundial','a descoberta do petróleo'],0,'Com o rei espanhol afastado, as elites coloniais formaram juntas de governo e depois romperam com a metrópole.'],
 ['Independências na América Latina',2,'De qual país europeu o Haiti era colônia (com o nome de Saint-Domingue)?',['França','Espanha','Portugal','Inglaterra'],0,'Saint-Domingue era a colônia mais lucrativa da França, com produção de açúcar baseada no trabalho escravizado.'],
 ['Independências na América Latina',3,'O que aconteceu com a América espanhola após as independências?',['fragmentou-se em vários países, apesar do projeto de união de Bolívar','formou um único grande país','voltou a ser colônia da Espanha','uniu-se ao Brasil em uma monarquia'],0,'Interesses regionais das elites levaram à formação de diversas repúblicas.'],

 ['Brasil no século XIX e período regencial',1,'Em que ano o Brasil declarou sua independência de Portugal?',['1822','1500','1888','1889'],0,'Em 7 de setembro de 1822. D. Pedro I tornou-se o primeiro imperador.'],
 ['Brasil no século XIX e período regencial',2,'Qual foi a duração do período regencial?',['de 1831, com a abdicação de D. Pedro I, até 1840, com o Golpe da Maioridade','de 1500 a 1530','de 1889 a 1930','de 1964 a 1985'],0,'Foi um intervalo de cerca de nove anos, marcado por revoltas em várias províncias.'],
 ['Brasil no século XIX e período regencial',2,'Por que o Brasil foi governado por regentes entre 1831 e 1840?',['porque D. Pedro II ainda era criança quando o pai abdicou','porque o Brasil virou república','porque D. Pedro I morreu em uma guerra','porque Portugal nomeou governadores'],0,'D. Pedro II tinha 5 anos em 1831. A Constituição exigia regentes até a maioridade dele.'],
 ['Brasil no século XIX e período regencial',2,'Qual revolta, liderada por estancieiros no Rio Grande do Sul, durou de 1835 a 1845?',['Farroupilha','Cabanagem','Balaiada','Sabinada'],0,'A Guerra dos Farrapos foi a mais longa revolta do período e chegou a proclamar uma república.'],
 ['Brasil no século XIX e período regencial',2,'Em que província ocorreu a Cabanagem (1835–1840)?',['Grão-Pará','Bahia','Maranhão','São Paulo'],0,'A Cabanagem teve grande participação de indígenas, negros e mestiços pobres (os “cabanos”).'],
 ['Brasil no século XIX e período regencial',3,'A Constituição de 1824 criou um quarto poder, exclusivo do imperador. Qual?',['o Poder Moderador','o Poder Eleitoral','o Poder Popular','o Poder Militar'],0,'Com o Poder Moderador, o imperador podia intervir nos outros poderes, o que concentrava a autoridade.'],

 ['Escravidão, resistências e abolição',1,'Em que ano foi assinada a Lei Áurea, que aboliu a escravidão no Brasil?',['1888','1822','1850','1871'],0,'Assinada em 13 de maio de 1888, fez do Brasil o último país das Américas a abolir a escravidão.'],
 ['Escravidão, resistências e abolição',2,'Qual foi o maior e mais conhecido quilombo do Brasil colonial, que teve Zumbi como líder?',['Palmares','Canudos','Contestado','Farroupilha'],0,'Palmares, na Serra da Barriga (atual Alagoas), resistiu por quase um século. O 20 de novembro, Dia da Consciência Negra, lembra Zumbi.'],
 ['Escravidão, resistências e abolição',2,'O que determinou a Lei Eusébio de Queirós, de 1850?',['a proibição do tráfico de africanos escravizados para o Brasil','a abolição da escravidão','a libertação dos idosos','a libertação dos filhos de mulheres escravizadas'],0,'O tráfico foi proibido, mas a escravidão continuou existindo no país.'],
 ['Escravidão, resistências e abolição',2,'O que estabeleceu a Lei do Ventre Livre, de 1871?',['que os filhos de mulheres escravizadas nascidos a partir dela seriam livres','a abolição imediata da escravidão','a proibição do tráfico negreiro','a libertação dos maiores de 60 anos'],0,'Na prática, muitas dessas crianças continuaram sob controle dos senhores até os 21 anos.'],
 ['Escravidão, resistências e abolição',2,'Quais foram formas de resistência das pessoas escravizadas?',['fugas, formação de quilombos, revoltas e preservação das culturas africanas','nenhuma, pois aceitavam a escravidão','apenas pedidos ao rei','somente greves em fábricas'],0,'A resistência foi constante: revoltas como a dos Malês (1835), quilombos, irmandades e a manutenção de religiões e costumes.'],
 ['Escravidão, resistências e abolição',3,'Qual foi um problema enfrentado pela população negra logo após a abolição?',['os libertos não receberam terras, indenização nem políticas de integração','todos receberam terras do governo','os ex-escravizados foram indenizados','o racismo deixou de existir'],0,'Sem apoio, muitos ficaram em condições precárias, e as desigualdades raciais persistem até hoje.'],
]};
