import type {SubjectBank} from './types.ts';

export const portugues:SubjectBank={subject:'Língua Portuguesa',items:[
 ['Leitura e interpretação de textos',1,'Leia: “Maria saiu cedo de casa levando guarda-chuva e casaco, mesmo com o céu ainda claro.” O que se pode inferir?',['Maria imaginava que o tempo poderia mudar.','Maria esqueceu o guarda-chuva.','Estava chovendo quando Maria saiu.','Maria não gosta de sair cedo.'],0,'O texto não diz que ia chover, mas levar guarda-chuva e casaco com o céu claro sugere que Maria esperava mudança no tempo. Isso é uma inferência.'],
 ['Leitura e interpretação de textos',2,'O tema de um texto é:',['o assunto central de que o texto trata','o título escolhido pelo autor','a primeira frase do texto','a opinião de um personagem'],0,'O tema é a ideia geral que atravessa o texto; o título pode ou não revelá-lo.'],
 ['Leitura e interpretação de textos',2,'Em “O time jogou tão mal que a torcida saiu antes do fim”, que relação de sentido a expressão “tão… que” estabelece?',['consequência','comparação','finalidade','oposição'],0,'A saída da torcida é consequência de o time ter jogado mal.'],
 ['Leitura e interpretação de textos',2,'Na frase “Aquele professor é uma enciclopédia ambulante”, a expressão destacada significa que o professor:',['sabe muito sobre muitos assuntos','carrega livros para todo lado','anda muito pela escola','escreveu uma enciclopédia'],0,'É uma metáfora: compara-se o professor a uma enciclopédia para indicar grande conhecimento.'],
 ['Leitura e interpretação de textos',3,'“Que ótimo! Choveu justo no dia do passeio.” Qual efeito de sentido predomina nessa fala?',['ironia, que expressa frustração','elogio sincero à chuva','informação neutra sobre o tempo','pedido de ajuda'],0,'A pessoa diz “que ótimo”, mas quer dizer o contrário: está frustrada. Dizer o oposto do que se pensa é ironia.'],
 ['Leitura e interpretação de textos',3,'Em “Pedro, que nunca perde um treino, faltou hoje”, qual informação está implícita?',['Pedro costuma ir aos treinos.','Pedro está doente.','Pedro não gosta de treinar.','O treino foi cancelado.'],0,'A oração “que nunca perde um treino” pressupõe que Pedro é assíduo. As demais opções não podem ser confirmadas pelo texto.'],

 ['Argumentação e artigo de opinião',1,'Em um artigo de opinião, a tese é:',['a ideia central que o autor defende','um dado estatístico','o título do jornal','a assinatura do autor'],0,'A tese é o ponto de vista principal; os argumentos servem para sustentá-la.'],
 ['Argumentação e artigo de opinião',2,'Qual frase apresenta um argumento baseado em dados?',['“Uma pesquisa com 2 mil estudantes indicou que quem lê todo dia escreve melhor.”','“Eu acho que ler é importante.”','“Ler é bom porque é bom.”','“Minha avó sempre dizia para ler.”'],0,'Só a primeira apoia a ideia em uma pesquisa. As outras são opinião pessoal, repetição da ideia ou relato sem comprovação.'],
 ['Argumentação e artigo de opinião',2,'Em “O projeto é caro; no entanto, traz benefícios duradouros”, o conectivo “no entanto” indica:',['oposição','adição','conclusão','explicação'],0,'“No entanto” equivale a “mas”, “porém”: contrapõe o custo aos benefícios.'],
 ['Argumentação e artigo de opinião',2,'Onde o artigo de opinião costuma ser publicado?',['em jornais, revistas e sites, com assinatura do autor','em bulas de remédio','em dicionários','em manuais de instrução'],0,'É um gênero jornalístico opinativo, assinado por quem defende o ponto de vista.'],
 ['Argumentação e artigo de opinião',3,'O contra-argumento, em um texto argumentativo, é:',['uma ideia contrária à tese, apresentada pelo autor para ser refutada','a repetição da tese com outras palavras','o título do texto','a lista de referências'],0,'Ao prever e responder a uma objeção, o autor fortalece sua própria tese.'],
 ['Argumentação e artigo de opinião',3,'Qual destas NÃO é uma estratégia argumentativa?',['usar rimas só para enfeitar o texto','dar exemplos','citar especialistas','fazer comparações'],0,'Exemplos, citações e comparações sustentam a tese. Rimas decorativas não acrescentam razões ao argumento.'],

 ['Coesão e coerência',1,'“Ana comprou um livro. Ela adorou o livro.” Qual palavra substitui “o livro” e evita a repetição? (Ela ___ adorou.)',['o','ela','lhe','seu'],0,'O pronome oblíquo “o” retoma “o livro”: “Ela o adorou.” Isso é coesão por referência.'],
 ['Coesão e coerência',2,'Complete com o conectivo adequado: “Estudei muito, ___ tirei nota baixa.”',['mas','por isso','portanto','porque'],0,'Há uma quebra de expectativa (estudar muito e tirar nota baixa), então o conectivo é de oposição: “mas”.'],
 ['Coesão e coerência',2,'Qual é o problema da frase “Ele estava muito cansado, por isso correu mais 10 km”?',['a relação de causa e consequência é ilógica','há erro de ortografia','falta pontuação','usa gíria'],0,'O cansaço não costuma ser motivo para correr mais. A frase fica incoerente.'],
 ['Coesão e coerência',2,'Em “Choveu muito. Isso atrasou a obra.”, o pronome “isso” retoma:',['o fato de ter chovido muito','a obra','o atraso','uma chuva futura'],0,'“Isso” resume a informação anterior inteira: a chuva forte.'],
 ['Coesão e coerência',3,'A coerência de um texto está ligada principalmente:',['ao sentido lógico e à unidade das ideias','ao uso de vírgulas','ao tamanho dos parágrafos','ao número de palavras'],0,'Coerência é a lógica do sentido. Coesão são as ligações formais (pronomes, conectivos) entre as partes.'],
 ['Coesão e coerência',3,'Qual conectivo introduz uma conclusão?',['logo','embora','caso','quando'],0,'“Logo” equivale a “portanto”. “Embora” indica concessão, “caso” condição e “quando” tempo.'],

 ['Orações e períodos',1,'Um período simples é formado por:',['uma única oração','duas orações','nenhum verbo','três orações ou mais'],0,'Cada oração se organiza em torno de um verbo (ou locução verbal). Período simples: um só verbo, uma oração.'],
 ['Orações e períodos',1,'Quantas orações há em “Cheguei, tomei banho e dormi”?',['3','1','2','4'],0,'Há três verbos (cheguei, tomei, dormi), portanto três orações.'],
 ['Orações e períodos',2,'Em “Estudo, mas não aprendo”, a segunda oração é coordenada:',['adversativa','aditiva','conclusiva','explicativa'],0,'O conectivo “mas” indica oposição: oração coordenada sindética adversativa.'],
 ['Orações e períodos',2,'Qual período é composto por subordinação?',['“Espero que você venha.”','“Ri e chorei.”','“Choveu.”','“Corri, pulei, gritei.”'],0,'“Que você venha” completa o sentido de “espero” (funciona como objeto direto): uma oração depende da outra.'],
 ['Orações e períodos',2,'Qual é o sujeito de “Chegaram as encomendas”?',['as encomendas','chegaram','sujeito oculto','oração sem sujeito'],0,'O sujeito pode vir depois do verbo: quem chegou? As encomendas.'],
 ['Orações e períodos',3,'Em “Saí cedo, pois tinha prova”, a oração “pois tinha prova” é coordenada:',['explicativa','adversativa','aditiva','alternativa'],0,'“Pois” antes do verbo introduz uma explicação para o que foi dito antes.'],

 ['Vozes verbais',1,'Qual é a voz passiva de “O cachorro mordeu o carteiro”?',['O carteiro foi mordido pelo cachorro.','O carteiro mordeu o cachorro.','O cachorro foi mordido.','O carteiro se mordeu.'],0,'Na passiva analítica, o objeto vira sujeito (o carteiro), usa-se ser + particípio (foi mordido) e o agente aparece com “por” (pelo cachorro).'],
 ['Vozes verbais',1,'Em “A menina se penteou”, o verbo está na voz:',['reflexiva','ativa','passiva analítica','passiva sintética'],0,'A menina pratica e recebe a ação ao mesmo tempo (penteou a si mesma).'],
 ['Vozes verbais',2,'Em “Vendem-se casas”, o verbo está na voz:',['passiva sintética','ativa','reflexiva','passiva analítica'],0,'Verbo + “se” (pronome apassivador) com sujeito paciente: casas são vendidas.'],
 ['Vozes verbais',2,'Em “O prêmio foi entregue pelo diretor”, qual é o agente da passiva?',['pelo diretor','o prêmio','foi entregue','entregue'],0,'O agente da passiva indica quem pratica a ação e vem introduzido por “por/pelo”.'],
 ['Vozes verbais',2,'Qual é a passiva analítica de “Os alunos organizaram a feira”?',['A feira foi organizada pelos alunos.','Organizou-se a feira.','A feira organizou os alunos.','Os alunos foram organizados.'],0,'“Organizou-se a feira” também é passiva, mas sintética. A analítica usa ser + particípio: “foi organizada”.'],
 ['Vozes verbais',3,'Uma manchete diz: “Vidros da escola são quebrados durante a noite”. Por que o jornal usou a passiva sem agente?',['porque o autor da ação é desconhecido ou o foco está no fato','para mostrar quem quebrou os vidros','porque a manchete é uma ordem','porque o verbo está no futuro'],0,'A passiva sem agente destaca o que aconteceu, e não quem fez. É útil quando o responsável é desconhecido.'],

 ['Pontuação e efeitos de sentido',1,'Qual frase está pontuada corretamente?',['Pedro, venha cá.','Pedro venha cá.','Pedro venha, cá.','Pedro: venha cá'],0,'“Pedro” é vocativo (quem é chamado) e deve ser separado por vírgula.'],
 ['Pontuação e efeitos de sentido',2,'Compare “Não, quero sair.” e “Não quero sair.”. O que muda?',['na primeira a pessoa quer sair; na segunda, não quer','nada, as frases são iguais','nas duas a pessoa quer sair','nas duas a pessoa não quer sair'],0,'Na primeira, o “não” responde a outra pergunta e a pessoa afirma que quer sair. A vírgula muda o sentido.'],
 ['Pontuação e efeitos de sentido',2,'As reticências (…) costumam indicar:',['interrupção, hesitação ou suspense','uma pergunta direta','o fim neutro de uma frase','uma enumeração'],0,'Elas sugerem que algo ficou por dizer, uma pausa ou dúvida.'],
 ['Pontuação e efeitos de sentido',2,'As aspas servem, entre outros usos, para:',['marcar citações ou palavras com sentido especial','separar o vocativo','indicar uma pergunta','separar o sujeito do verbo'],0,'Aspas destacam falas citadas, títulos, estrangeirismos ou ironia.'],
 ['Pontuação e efeitos de sentido',3,'A frase “Os alunos da escola, fizeram a prova.” está:',['incorreta, porque não se separa sujeito e verbo com vírgula','correta, porque a vírgula é obrigatória','correta, porque há vocativo','incorreta, porque falta ponto de exclamação'],0,'“Os alunos da escola” é o sujeito de “fizeram”. Não se usa vírgula entre sujeito e verbo.'],
 ['Pontuação e efeitos de sentido',3,'Em “Comprei três frutas: maçã, pera e uva.”, os dois-pontos indicam:',['uma enumeração que explica o que foi dito','uma interrupção','uma exclamação','o início de um diálogo'],0,'Os dois-pontos anunciam a lista das três frutas.'],

 ['Gêneros jornalísticos e digitais',1,'Qual é o principal objetivo de uma notícia?',['informar um fato recente de forma objetiva','convencer o leitor da opinião do autor','ensinar a montar um objeto','contar uma história inventada'],0,'A notícia relata fatos atuais. A opinião é própria de gêneros como o artigo de opinião e o editorial.'],
 ['Gêneros jornalísticos e digitais',2,'O lide (primeiro parágrafo) de uma notícia costuma responder:',['o quê, quem, quando, onde, como e por quê','apenas a opinião do jornalista','o preço do jornal','quem é o editor-chefe'],0,'O lide resume as informações essenciais logo no começo.'],
 ['Gêneros jornalísticos e digitais',2,'Qual é a principal diferença entre reportagem e notícia?',['a reportagem aprofunda o assunto, com mais pesquisa, entrevistas e dados','a reportagem é sempre ficcional','a notícia é sempre mais longa','não há diferença'],0,'A notícia informa o fato; a reportagem investiga e contextualiza o tema.'],
 ['Gêneros jornalísticos e digitais',2,'A manchete é:',['o título principal de uma notícia ou da capa','o último parágrafo','a legenda da foto','o nome do jornal'],0,'A manchete chama a atenção para o fato mais importante.'],
 ['Gêneros jornalísticos e digitais',2,'Qual gênero digital combina imagem e texto curto, costuma ser humorístico e se espalha rapidamente nas redes?',['meme','editorial','ata','bula'],0,'O meme depende de referências compartilhadas e circula com rapidez nas redes sociais.'],
 ['Gêneros jornalísticos e digitais',3,'A charge é um gênero que:',['usa desenho e humor para criticar fatos atuais','explica tecnicamente um produto','noticia fatos sem imagens','é uma carta formal'],0,'A charge comenta criticamente acontecimentos do momento, por isso depende do contexto.'],

 ['Análise de fontes e checagem de informações',1,'Você recebeu uma notícia surpreendente pelo celular. Qual é a melhor primeira atitude?',['verificar a fonte e procurar a informação em veículos confiáveis','compartilhar rapidamente','acreditar se tiver muitas curtidas','comentar sem ler'],0,'Checar a origem e comparar com outras fontes evita espalhar desinformação.'],
 ['Análise de fontes e checagem de informações',2,'Qual é um sinal de possível notícia falsa?',['título alarmista, sem autor e sem data','várias fontes citadas','data e autoria claras','link para um site oficial'],0,'Apelo emocional e ausência de autoria e data são alertas comuns de desinformação.'],
 ['Análise de fontes e checagem de informações',2,'Por que é importante conferir a data de uma notícia?',['porque notícias antigas podem ser compartilhadas como se fossem atuais','porque a data não importa','para saber o preço da notícia','para saber quantas pessoas leram'],0,'Um fato verdadeiro fora de época pode enganar o leitor.'],
 ['Análise de fontes e checagem de informações',2,'Para que servem as agências de checagem de fatos?',['para verificar se informações que circulam são verdadeiras','para vender produtos','para publicar memes','para hospedar vídeos'],0,'Elas investigam boatos e publicam a verificação com as fontes consultadas.'],
 ['Análise de fontes e checagem de informações',3,'O que é uma imagem “fora de contexto”?',['uma foto verdadeira usada para ilustrar outro fato, induzindo ao erro','uma foto em baixa resolução','uma foto com legenda correta','uma foto de acervo público com crédito'],0,'A imagem é real, mas a legenda ou o contexto são falsos. A busca reversa de imagens ajuda a descobrir a origem.'],
 ['Análise de fontes e checagem de informações',3,'Uma fonte primária é:',['um documento ou relato produzido por quem viveu ou registrou diretamente o fato','um comentário de terceiros em rede social','um resumo feito por um influenciador','um boato repassado'],0,'Fontes primárias (documentos, dados oficiais, testemunhos) são a base da verificação; as demais dependem delas.'],
]};
