// Questões autorais introdutórias para o 8º ano, por área, sem atribuição de códigos BNCC específicos.
export const starterQuestions=[
 ['Matemática','Potenciação','Quanto vale 2³ × 2²?','32','Somam-se os expoentes das potências de mesma base: 2⁵ = 32.'],
 ['Matemática','Porcentagens','Um produto de R$ 80 recebeu desconto de 25%. Qual é o preço final?','R$ 60','25% de 80 são 20; 80 − 20 = 60.'],
 ['Matemática','Equações','Resolva 3x + 5 = 20.','x = 5','Subtraia 5 e divida por 3.'],
 ['Matemática','Geometria','Qual é a soma dos ângulos internos de um quadrilátero?','360°','O quadrilátero pode ser dividido em dois triângulos de 180°.'],
 ['Língua Portuguesa','Interpretação','O que caracteriza uma opinião em um texto argumentativo?','Um ponto de vista defendido por argumentos.','A opinião expressa uma posição que pode ser sustentada por razões e evidências.'],
 ['Língua Portuguesa','Coesão','Na frase “Ela estudou, portanto foi bem”, que relação “portanto” estabelece?','Conclusão.','O conectivo introduz uma consequência ou conclusão.'],
 ['Língua Portuguesa','Vozes verbais','Passe para a voz passiva: “A turma resolveu a questão”.','A questão foi resolvida pela turma.','O objeto da voz ativa se torna sujeito paciente.'],
 ['Língua Portuguesa','Fonte','Por que verificar a fonte e a data de uma notícia?','Para avaliar sua confiabilidade e atualidade.','Autoria e data ajudam a contextualizar e conferir a informação.'],
 ['Ciências','Energia','Cite uma fonte renovável de energia.','Energia solar.','A energia solar é reposta continuamente pela radiação do Sol.'],
 ['Ciências','Eletricidade','Qual é a unidade de medida da potência elétrica?','Watt (W).','Potência indica a taxa de consumo ou transformação de energia.'],
 ['Ciências','Lua','Por que vemos diferentes fases da Lua?','Porque vemos porções diferentes da face iluminada pelo Sol ao longo de sua órbita.','A geometria entre Sol, Terra e Lua muda a parte iluminada visível.'],
 ['Ciências','Clima','Qual a diferença entre tempo atmosférico e clima?','Tempo é a condição momentânea; clima descreve padrões de longo prazo.','Clima depende de observações prolongadas.'],
 ['História','Iluminismo','Qual ideia iluminista defendia limitar o poder absoluto?','A separação dos poderes.','A divisão dos poderes ajuda a impedir a concentração do poder.'],
 ['História','Revolução Industrial','Que mudança marcou a produção na Revolução Industrial?','A mecanização da produção.','Máquinas e fábricas alteraram a forma de produzir.'],
 ['História','Revolução Francesa','Em que país ocorreu a Revolução Francesa?','França.','O processo revolucionário começou na França no fim do século XVIII.'],
 ['História','Abolição','Em que ano foi assinada a Lei Áurea no Brasil?','1888.','A lei aboliu juridicamente a escravidão, sem assegurar igualdade social.'],
 ['Geografia','Migração','O que é migração?','Deslocamento de pessoas entre lugares.','Pode ocorrer dentro de um país ou entre países.'],
 ['Geografia','Urbanização','O que significa urbanização?','Aumento da população urbana e expansão das cidades.','Envolve mudanças demográficas e espaciais.'],
 ['Geografia','América Latina','Cite um país da América Latina além do Brasil.','Argentina.','A Argentina integra a América Latina.'],
 ['Geografia','Meio ambiente','Qual consequência pode resultar do desmatamento?','Perda de biodiversidade.','A retirada de vegetação destrói habitats.'],
 ['Língua Inglesa','Comparatives','Complete: “My city is ___ than yours” usando big.','bigger','O comparativo de big duplica a consoante final e acrescenta -er.'],
 ['Língua Inglesa','Future','Como traduzir “I will study tomorrow”?','Eu estudarei amanhã.','Will indica uma ação futura nesse contexto.'],
 ['Língua Inglesa','Reading','O que significa “although” em português?','Embora.','A conjunção indica contraste.'],
 ['Língua Inglesa','Modal verbs','Qual verbo modal pode expressar possibilidade em “It ___ rain”?','might','Might indica possibilidade.'],
 ['Arte','Artes visuais','Cite um elemento da linguagem visual.','Cor.','Cor é um elemento visual, assim como linha e forma.'],
 ['Arte','Música','O que é ritmo na música?','Organização das durações e acentos dos sons.','O ritmo organiza eventos sonoros no tempo.'],
 ['Arte','Teatro','Como se chama a pessoa que interpreta uma personagem?','Ator ou atriz.','A interpretação dá vida à personagem em cena.'],
 ['Arte','Dança','Por que o contexto cultural importa na análise de uma dança?','Porque ajuda a compreender seus significados e origens.','Práticas corporais carregam histórias e identidades.'],
 ['Educação Física','Saúde','Cite um benefício da atividade física regular.','Melhora da saúde cardiovascular.','A prática regular pode favorecer o condicionamento.'],
 ['Educação Física','Esportes','Por que respeitar regras em um jogo coletivo?','Para garantir justiça e segurança.','As regras orientam a convivência e o jogo.'],
 ['Educação Física','Jogos','Qual é a diferença entre cooperação e competição?','Cooperação busca um objetivo conjunto; competição compara desempenhos.','As duas dinâmicas podem coexistir em jogos.'],
 ['Educação Física','Segurança','O que fazer antes de uma prática corporal de aventura?','Avaliar riscos e usar equipamentos de segurança.','Planejamento reduz acidentes.'],
 ['Matemática','Potenciação e radiciação','Qual é a raiz quadrada de 144?','12','12 × 12 = 144.'],
 ['Matemática','Notação científica','Escreva 4.500.000 em notação científica.','4,5 × 10⁶','A vírgula desloca seis casas para a esquerda.'],
 ['Matemática','Notação científica','Quanto vale 3 × 10⁴ na escrita decimal?','30000','10⁴ vale 10.000; multiplicando por 3 resulta 30.000.'],
 ['Matemática','Porcentagens e juros simples','Qual é 15% de 200?','30','0,15 × 200 = 30.'],
 ['Matemática','Expressões algébricas e produtos notáveis','Qual é o valor de 2x + 3 quando x = 4?','11','2 × 4 + 3 = 11.'],
 ['Matemática','Expressões algébricas e produtos notáveis','Desenvolva (a + b)².','a² + 2ab + b²','O quadrado da soma inclui os quadrados e o dobro do produto.'],
 ['Matemática','Equações do 1º grau e sistemas','Se x + y = 10 e x − y = 2, quanto vale x?','6','Somando as equações, 2x = 12.'],
 ['Matemática','Equações do 1º grau e sistemas','Resolva 5x − 10 = 0.','x = 2','Some 10 e divida por 5.'],
 ['Matemática','Geometria: ângulos, polígonos e congruência','Dois ângulos suplementares somam quantos graus?','180°','Ângulos suplementares completam um ângulo raso.'],
 ['Matemática','Geometria: ângulos, polígonos e congruência','Qual é a soma dos ângulos internos de um triângulo plano?','180°','Uma propriedade fundamental da geometria euclidiana plana.'],
 ['Matemática','Área de figuras planas','Qual é a área de um retângulo de 8 cm por 5 cm?','40 cm²','Área = base × altura = 8 × 5.'],
 ['Matemática','Área de figuras planas','Qual é a área de um triângulo com base 10 cm e altura 6 cm?','30 cm²','Área = base × altura ÷ 2.'],
 ['Matemática','Probabilidade e estatística','Qual é a probabilidade de sair cara em uma moeda equilibrada?','1/2','Há dois resultados igualmente prováveis.'],
 ['Matemática','Probabilidade e estatística','Qual é a média de 4, 6 e 8?','6','Some 18 e divida por 3.'],
] as const;
