import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const materials = sqliteTable('materials', {id:text('id').primaryKey(), owner:text('owner').notNull(), title:text('title').notNull(), kind:text('kind').notNull(), content:text('content').notNull().default(''), objectKey:text('object_key'), processingStatus:text('processing_status').notNull().default('pending'), createdAt:integer('created_at').notNull()}, t=>[index('idx_materials_owner_created').on(t.owner,t.createdAt)]);
export const plans = sqliteTable('plans', {id:text('id').primaryKey(), owner:text('owner').notNull(), title:text('title').notNull(), examDate:text('exam_date'), target:text('target'), createdAt:integer('created_at').notNull()}, t=>[index('idx_plans_owner_created').on(t.owner,t.createdAt)]);
export const topics = sqliteTable('topics', {id:text('id').primaryKey(), planId:text('plan_id').notNull().references(()=>plans.id), title:text('title').notNull(), status:text('status').notNull().default('pending'), position:integer('position').notNull().default(0), week:integer('week').notNull().default(1)}, t=>[index('idx_topics_plan_id').on(t.planId)]);
export const questions = sqliteTable('questions', {id:text('id').primaryKey(), owner:text('owner').notNull(), topicId:text('topic_id'), prompt:text('prompt').notNull(), answer:text('answer').notNull(), topicLabel:text('topic_label'), subject:text('subject'), explanation:text('explanation'), source:text('source'), createdAt:integer('created_at').notNull()}, t=>[index('idx_questions_owner_created').on(t.owner,t.createdAt)]);
export const attempts = sqliteTable('attempts', {id:text('id').primaryKey(), owner:text('owner').notNull(), questionId:text('question_id').notNull().references(()=>questions.id), response:text('response').notNull(), correct:integer('correct',{mode:'boolean'}).notNull(), feedback:text('feedback'), gradingMethod:text('grading_method').notNull().default('exact'), createdAt:integer('created_at').notNull()}, t=>[index('idx_attempts_owner_created').on(t.owner,t.createdAt),index('idx_attempts_question_id').on(t.questionId)]);
export const chatMessages = sqliteTable('chat_messages', {id:text('id').primaryKey(),owner:text('owner').notNull(),role:text('role').notNull(),content:text('content').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_chat_owner_created').on(t.owner,t.createdAt)]);
export const studySessions = sqliteTable('study_sessions', {id:text('id').primaryKey(),owner:text('owner').notNull(),subject:text('subject').notNull(),durationSeconds:integer('duration_seconds').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_sessions_owner_created').on(t.owner,t.createdAt)]);
export const resourceCatalog=sqliteTable('resource_catalog',{id:text('id').primaryKey(),subject:text('subject').notNull(),topic:text('topic').notNull(),title:text('title').notNull(),provider:text('provider').notNull(),kind:text('kind').notNull(),url:text('url').notNull(),sourceUrl:text('source_url').notNull(),usageNote:text('usage_note').notNull(),verifiedAt:text('verified_at').notNull()},t=>[index('idx_resources_subject_topic').on(t.subject,t.topic)]);
