import {env} from 'cloudflare:workers';
import {getDb} from '../../../db';
import {materials,plans,topics,questions,attempts,resourceCatalog} from '../../../db/schema';
import {eq,and,desc,inArray} from 'drizzle-orm';
import {starterQuestions} from '../../../lib/question-bank';
import {resources} from '../../../lib/resources';
import {curriculum} from '../../../lib/curriculum';

function identity(r:Request){return r.headers.get('oai-authenticated-user-id')}
function fail(message:string,status=400){return Response.json({error:message},{status})}
export async function GET(r:Request){const owner=identity(r);if(!owner)return fail('Entre na sua conta para usar o painel.',401);try{const db=getDb();const [m,p,q,a]=await Promise.all([db.select().from(materials).where(eq(materials.owner,owner)).orderBy(desc(materials.createdAt)),db.select().from(plans).where(eq(plans.owner,owner)).orderBy(desc(plans.createdAt)),db.select().from(questions).where(eq(questions.owner,owner)).orderBy(desc(questions.createdAt)),db.select().from(attempts).where(eq(attempts.owner,owner)).orderBy(desc(attempts.createdAt))]);const [t,links]=await Promise.all([p.length?db.select().from(topics).where(inArray(topics.planId,p.map(v=>v.id))):Promise.resolve([]),db.select().from(resourceCatalog)]);return Response.json({materials:m,plans:p,topics:t,questions:q,attempts:a,resources:links.length?links:resources})}catch(e){console.error('study GET',e);return fail('Os dados estão temporariamente indisponíveis.',503)}}
export async function POST(r:Request){const owner=identity(r);if(!owner)return fail('Entre na sua conta para salvar.',401);try{const body=await r.json() as Record<string,unknown>;const op=String(body.op||'');const db=getDb();const id=crypto.randomUUID();const now=Date.now();const str=(v:unknown,max=10000)=>String(v??'').trim().slice(0,max);
if(op==='material'){const title=str(body.title,160),kind=str(body.kind,30),content=str(body.content,100000);if(!title||!['anotações','prova antiga','vídeo','link','PDF'].includes(kind))return fail('Informe título e tipo válidos.');let objectKey:null|string=null;if(body.file){return fail('Envie arquivos pelo formulário de upload.')}const [row]=await db.insert(materials).values({id,owner,title,kind,content,objectKey,createdAt:now}).returning();return Response.json({item:row})}
if(op==='plan'){const title=str(body.title,160);if(!title)return fail('Informe o nome da prova.');const subjects=str(body.subjects,5000).split('\n').map(x=>x.trim()).filter(Boolean).slice(0,50);if(!subjects.length)return fail('Informe ao menos um tema.');const date=str(body.examDate,10);const [row]=await db.insert(plans).values({id,owner,title,examDate:date||null,target:str(body.target,40)||null,createdAt:now}).returning();await db.insert(topics).values(subjects.map((title,position)=>({id:crypto.randomUUID(),planId:id,title,position})));return Response.json({item:row})}
if(op==='topic'){const topicId=str(body.id,80);const status=str(body.status,20);if(!['pending','done'].includes(status))return fail('Estado inválido.');const record=await db.select({id:topics.id}).from(topics).innerJoin(plans,eq(topics.planId,plans.id)).where(and(eq(topics.id,topicId),eq(plans.owner,owner))).get();if(!record)return fail('Tema não encontrado.',404);await db.update(topics).set({status}).where(eq(topics.id,topicId));return Response.json({ok:true})}
if(op==='catalog'){await db.insert(resourceCatalog).values(resources).onConflictDoNothing();return Response.json({count:resources.length})}
if(op==='path'){const subject=str(body.subject,80);const list=curriculum[subject];if(!list)return fail('Disciplina inválida.');const previous=await db.select().from(plans).where(and(eq(plans.owner,owner),eq(plans.title,`Trilha de ${subject} · 8º ano`))).limit(1);if(previous.length)return Response.json({planId:previous[0].id,count:list.length,notice:'Trilha já existe.'});await db.insert(resourceCatalog).values(resources).onConflictDoNothing();const planId=crypto.randomUUID();await db.insert(plans).values({id:planId,owner,title:`Trilha de ${subject} · 8º ano`,examDate:null,target:'Revisar, praticar e corrigir',createdAt:Date.now()});await db.insert(topics).values(list.map((title,position)=>({id:crypto.randomUUID(),planId,title,position,week:Math.floor(position/2)+1})));return Response.json({planId,count:list.length})}
if(op==='seed'){const existing=await db.select({prompt:questions.prompt}).from(questions).where(and(eq(questions.owner,owner),eq(questions.source,'Banco inicial 8º ano')));const known=new Set(existing.map(x=>x.prompt));const entries=starterQuestions.filter(([, ,prompt])=>!known.has(prompt)).map(([subject,topic,prompt,answer,explanation])=>({id:crypto.randomUUID(),owner,topicId:null,topicLabel:topic,prompt,answer,explanation,subject,source:'Banco inicial 8º ano',createdAt:Date.now()}));if(entries.length)await db.insert(questions).values(entries);return Response.json({count:entries.length,notice:entries.length?'Banco atualizado.':'Banco inicial já instalado.'})}
if(op==='question'){const prompt=str(body.prompt,3000),answer=str(body.answer,3000);if(!prompt||!answer)return fail('Informe a pergunta e a resposta.');const [row]=await db.insert(questions).values({id,owner,prompt,answer,topicId:null,topicLabel:str(body.topic,160)||null,subject:str(body.subject,80)||null,createdAt:now}).returning();return Response.json({item:row})}
if(op==='attempt'){const questionId=str(body.questionId,80),response=str(body.response,3000);const question=await db.select().from(questions).where(and(eq(questions.id,questionId),eq(questions.owner,owner))).get();if(!question)return fail('Questão não encontrada.',404);if(!response)return fail('Escreva sua resposta.');const correct=response.toLocaleLowerCase('pt-BR').replace(/\s+/g,' ').trim()===question.answer.toLocaleLowerCase('pt-BR').replace(/\s+/g,' ').trim();await db.insert(attempts).values({id,owner,questionId,response,correct,createdAt:now});return Response.json({correct,answer:question.answer,notice:'Correção por correspondência exata; respostas equivalentes precisam de revisão humana.'})}
if(op==='delete'){const table=str(body.table,30),target=str(body.id,80);if(table==='material'){const row=await db.select().from(materials).where(and(eq(materials.id,target),eq(materials.owner,owner))).get();if(row){await db.delete(materials).where(eq(materials.id,target));if(row.objectKey)await env.BUCKET!.delete(row.objectKey)}}else if(table==='question'){const row=await db.select().from(questions).where(and(eq(questions.id,target),eq(questions.owner,owner))).get();if(row){await db.delete(attempts).where(eq(attempts.questionId,target));await db.delete(questions).where(eq(questions.id,target))}}else if(table==='plan'){const p=await db.select().from(plans).where(and(eq(plans.id,target),eq(plans.owner,owner))).get();if(p){await db.delete(topics).where(eq(topics.planId,target));await db.delete(plans).where(eq(plans.id,target))}}else return fail('Tipo inválido.');return Response.json({ok:true})}
return fail('Ação não reconhecida.')}catch(e){console.error('study POST',e);return fail('Não foi possível salvar. Tente novamente.',503)}}
